### PR TITLE
Development

### PR DESCRIPTION
**Pull request by gferrarocamus**

### CODE REVIEW

**Comment by talihomz** [comment]
## Great Work on Enumerable Extensions, Linter has Errors
---

Implementation of the extensions works Ok. Fix the linter problems listed above for a thumbs up on this.

**Comment by gferrarocamus** [comment]
Thank you, @talihomz! We've fixed almost all the linter issues. 

One question: We've broken down our original methods into shorter ones, but we're still getting a few "method too long" warnings. Do you have any suggestions to solve this? Breaking them down even further, or any other alternatives? 

Any input about this will be much appreciated!

**Comment by talihomz** [comment]
Hi @gferrarocamus!

The methods the linter is pointing out to are actually too long as indicated. They need to be shortened for them to pass.
We can shorten [one of these methods](https://github.com/gferrarocamus/enumerable-methods/blob/268f989230226b2605d351d82c9929d0c091c21b/main.rb#L213-L230) as follows:
```
def my_none_block(result)
  if is_a? Array
    my_each do |item|
      if yield item
        result = false
        break
      end
    end
  elsif is_a? Hash
    my_each do |k, v|
      if yield(k, v)
        result = false
        break
      end
    end
  end
  result
end
```
In the above, we are repeating logic based on whether or not the data structure is a Hash. Instead, we can reduce it to 7 lines of Ruby as follows:
```
def my_none_block(result)
  my_each do | k, v |
    if (is_a? Array && yield(k)) || (is_a? Hash && yield(k,v))    # for the case of an array, v will be empty
      result = false
      break
    end
  end
end
```

Try this out and let me know if the linter still complains. Also, try and find ways to do the same for the other long methods.

**Comment by gferrarocamus** [comment]
Thanks, @talihomz! That worked like a charm.

**Comment by talihomz** [comment]
👍

**Pull request merged**
